project:
  title: "SCHOOL Water Module"
  type: website
  output-dir: docs
format:
  html:
    embed-resources: true
    theme: sandstone
    css: "https://github.com/ciesin-geospatial/TOPSTSCHOOL/blob/main/custom.scss"
    toc: true
    toc-title: Contents
    toc-location: left
lightbox: true
execute: 
  warning: false

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Lessons"
        menu:
          - text: "WSIM Data Acquisition and Processing"
            url: https://ciesin-geospatial.github.io/TOPSTSCHOOL-module-1-water/wsim-gldas-acquisition.html
          - text: "WSIM Data Visualization and Exploration"
            url: https://ciesin-geospatial.github.io/TOPSTSCHOOL-module-1-water/wsim-gldas-vis.html
          - text: "MODIS NRT Flood Data Acquisition Exploration"
            url: https://ciesin-geospatial.github.io/TOPSTSCHOOL-module-1-water/lance-modis-nrt-global-flood-mcdwd-f3.html
          - text: "Interactive NYC School Lead Data Explorer"
            url: https://ciesin-geospatial.github.io/TOPSTSCHOOL-module-1-water/exposure_to_lead_in_schools_nys.html
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ciesin-geospatial/TOPSTSCHOOL
          - text: Report a Bug
            url:  https://github.com/ciesin-geospatial/TOPSTSCHOOL/issues
      - icon: globe
        href: https://ciesin-geospatial.github.io/TOPSTSCHOOL/
        text: "TOPSTSCHOOL GitHub Home Page"
      - icon: youtube
        href: https://www.youtube.com/channel/UCOIrczFd7_ht2bNUQ3qnM8w
        text: "Youtube Channel"
